### PR TITLE
feat(frontend): add landing page

### LINKED ISSUE #4: Create a landing page for the project where to fill the data to generate the image
We need to create a landing page that may render a few project information.

Through the landing page, you can also generate your wrapped image.

We must decide which solution is better.

- use a Login with GitHub button (as already present in main) and use it to retrieve the user who wants to generate the image
- use a form where the user may be able to insert its GitHub handle to receive its image

### PR DESCRIPTION
**Pull request by TheJoin95**
Closes #4

### CODE REVIEW

**Comment by TheJoin95** [comment]
image

Can we merge this as a start?

**Comment by nicpuppa** [comment]
@TheJoin95 if the user is not logged what we want to show ?

**Comment by 404answernotfound** [comment]
> @TheJoin95 if the user is not logged what we want to show ?
> 
> based on what we said yesterday, we don't need the user to enter the nickname. So I would just leave the "wrap me up" button

yeah, for this first version let's stick with login, we will use the "input" in the next iteration when repos are wrapped. You guys good with this?

**Review by 404answernotfound — APPROVED** [review]
approved but let's run first iteration of the app with the login instead of search by username

**Comment by 404answernotfound** [comment]
also, @TheJoin95 nice job mate

**Comment by TheJoin95** [comment]
Yep, agree, can we merge this so in the other pr we can rebase and use just the button attached to the sign in?

**Comment by 404answernotfound** [comment]
> Yep, agree, can we merge this so in the other pr we can rebase and use just the button attached to the sign in?

you can merge, already approved 🍡

**Pull request merged**
