### PR TITLE
Add favicon and basic progressive web app requirement

### PR DESCRIPTION
**Pull request by ehsanghaffar**
Hello 👋🏻
I added the Favicon component and also did the initial configuration for the PWA, just un-comment it.
I hope I have been helpful.

### CODE REVIEW

**Review by TheJoin95 — CHANGES_REQUESTED** [review]
Thank you for your contribution 
Some favicon are incorrect, could you check again? Eventually ask to our discord which logo should be added 

Also, I don't think a pwa would be useful

**Comment by 404answernotfound** [comment]
Thank you @ehsanghaffar , could you please review what @TheJoin95 said?

**Comment by ehsanghaffar** [comment]
Sure, because I didn't have an icon, I just put a placeholder.

**Comment by nicpuppa** [comment]
I close this PR because the favicon has already been placed

**Pull request closed without merging**
